In [3]:
import numpy as np

In [1]:
#Valid Suduko

In [39]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [40]:
a = np.sum(s,axis=1)
for i in a:
    if i != 45:
        print ("not valid")
else:
        print ("valid column")
        

valid column


In [41]:
c=np.sum(s,axis=0)
for i in c:
    if i != 45:
        print("not valid")
else:
    print("valid column")

valid column


In [42]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n= (s[i:i+3,j:j+3])
        print(n.sum())
        

45
45
45
45
45
45
45
45
45


In [43]:
#General Question 

In [44]:
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [45]:
data.shape

(5, 3)

In [46]:
np.mean(data[:,0])

np.float64(18.4)

In [47]:
data[:,1]

array([85, 92, 76, 65, 90])

In [48]:
np.max(data[:,2])

np.int64(95)

In [49]:
data[ data[:,1]>90]

array([[19, 92, 88]])

In [50]:
data[:,2] += 5
data

array([[ 18,  85,  83],
       [ 19,  92,  93],
       [ 17,  76, 100],
       [ 18,  65,  75],
       [ 20,  90,  90]])

In [55]:
len(data[data[:,0]<19])


3

In [59]:
np.mean(data[:,1:],axis = 0)

array([81.6, 88.2])

In [60]:
data[(data[:,1]>=80) &(data[:,2]>=80)]

array([[18, 85, 83],
       [19, 92, 93],
       [20, 90, 90]])

In [69]:
data

array([[  0,   0,   0],
       [ 19,  92,  93],
       [ 17,  76, 100],
       [  0,   0,   0],
       [ 20,  90,  90]])

In [70]:
data[:,2][data[:,2]<85] = 0
data

array([[  0,   0,   0],
       [ 19,  92,  93],
       [ 17,  76, 100],
       [  0,   0,   0],
       [ 20,  90,  90]])