In [1]:
import numpy as np

In [3]:
#Basic array creaction

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
l = [[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#Array generation function

In [12]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [15]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [19]:
#Random generation function

In [29]:
arr = np.random.rand(10,2)
arr

array([[ 0.59300754, -0.85525473],
       [ 0.15176093, -0.07712992],
       [ 0.3772571 ,  0.56650459],
       [ 0.83146887,  2.12021954],
       [ 0.07372111, -1.15798087],
       [ 0.20135506, -1.41446226],
       [-0.87653797, -0.33253269],
       [ 0.89908597, -0.45401755],
       [ 0.88237138,  0.01294383],
       [-1.42489312, -0.56708772]])

In [30]:
arr = np.random.randn(10,2)
arr

array([[ 0.49582825,  0.66307336],
       [-0.31434928, -0.0192889 ],
       [ 1.24078989, -0.36794871],
       [ 0.13301925,  0.15904478],
       [ 1.42331993,  0.75119666],
       [-0.47117069, -2.57440856],
       [ 1.07128971,  0.61792219],
       [-0.6128816 ,  0.72269512],
       [-1.55328067,  0.22475629],
       [ 0.51778521,  1.80821097]])

In [31]:
np.random.randint(10,20,10)

array([17, 16, 19, 15, 16, 17, 19, 17, 11, 15], dtype=int32)

In [32]:
#Array attributes

In [33]:
arr  = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.shape

(3, 3)

In [35]:
arr.size

9

In [36]:
arr.dtype

dtype('int64')

In [37]:
#array method

In [38]:
arr.min()

np.int64(1)

In [39]:
arr.max()

np.int64(9)

In [40]:
arr.sum()

np.int64(45)

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [46]:
arr.mean()

np.float64(5.0)

In [47]:
arr.std()

np.float64(2.581988897471611)

In [49]:
arr.argmax()

np.int64(8)

In [50]:
arr.argmin()

np.int64(0)

In [51]:
#reshaping and resizing

In [53]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])